"""HU-10: tablas permisos y usuario_permisos

Revision ID: e57695beaef9
Revises: e8bdfb173fb7
Create Date: 2026-07-10 08:52:00.168117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57695beaef9'
down_revision = 'e8bdfb173fb7'
branch_labels = None
depends_on = None


permisos_table = sa.table(
    "permisos",
    sa.column("codigo", sa.String),
    sa.column("descripcion", sa.String),
)

_CATALOGO_INICIAL = [
    {
        "codigo": "checkin.ver_dispositivos_bloqueados",
        "descripcion": "Ver la lista de dispositivos de kiosko bloqueados (GET /checkin/dispositivos-bloqueados).",
    },
    {
        "codigo": "checkin.desbloquear_dispositivo",
        "descripcion": "Desbloquear manualmente un dispositivo de kiosko (POST /checkin/desbloquear/{device_id}).",
    },
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permisos_codigo'), 'permisos', ['codigo'], unique=True)
    op.create_index(op.f('ix_permisos_id'), 'permisos', ['id'], unique=False)
    op.create_table('usuario_permisos',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'permiso_id')
    )
    # NOTA: autogenerate detectó como "removido" el índice único parcial
    # ix_checkins_usuario_dia_activo de HU-01 (creado con SQL crudo, Alembic no
    # lo reconoce como metadata ORM) y proponía un DROP INDEX — se quita a
    # mano, igual que en e8bdfb173fb7 (HU-02); ese índice sigue vigente.
    # ### end Alembic commands ###
    op.bulk_insert(permisos_table, _CATALOGO_INICIAL)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_permisos')
    op.drop_index(op.f('ix_permisos_id'), table_name='permisos')
    op.drop_index(op.f('ix_permisos_codigo'), table_name='permisos')
    op.drop_table('permisos')
    # ### end Alembic commands ###
